export const FALLBACK_MENU_CONFIG = {
    groups: [
        {
            id: 'fallback-overview',
            slug: 'overview',
            name: 'Overview',
            icon: 'Monitor',
            priority: 10,
            items: [
                { id: 'dashboard', slug: 'dashboard', name: 'Dashboard', icon: 'BarChart3', href: '/dashboard', section: null, priority: 10, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
                { id: 'spaces', slug: 'spaces', name: 'Spaces', icon: 'Layout', href: '/spaces', section: null, priority: 20, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
                { id: 'projects', slug: 'projects', name: 'Projects', icon: 'Kanban', href: '/admin/projects', section: null, priority: 30, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
                { id: 'tasks', slug: 'tasks', name: 'Tasks', icon: 'CheckCircle2', href: '/tasks', section: null, priority: 40, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
                { id: 'workflows', slug: 'workflows', name: 'Workflows', icon: 'GitBranch', href: '/workflows', section: null, priority: 50, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
                { id: 'assignments', slug: 'assignments', name: 'Assignments', icon: 'CheckCircle2', href: '/assignments', section: null, priority: 60, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
            ],
        },
        {
            id: 'fallback-tools',
            slug: 'tools',
            name: 'Tools',
            icon: 'FlaskConical',
            priority: 20,
            items: [
                { id: 'ai-chat-ui', slug: 'ai-chat-ui', name: 'AI Chat', icon: 'MessageCircle', href: '/tools/ai-chat-ui', section: 'AI', priority: 10, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
                { id: 'bi', slug: 'bi', name: 'Business Intelligence', icon: 'BarChart3', href: '/tools/bi', section: 'Analytics', priority: 15, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
                { id: 'marketplace', slug: 'marketplace', name: 'Marketplace', icon: 'Store', href: '/marketplace', section: 'Extensions', priority: 20, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
                { id: 'knowledge', slug: 'knowledge', name: 'Knowledge', icon: 'BookOpen', href: '/knowledge', section: 'Extensions', priority: 30, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
                { id: 'pwa-builder', slug: 'pwa-builder', name: 'PWA Builder', icon: 'Smartphone', href: '/tools/pwa', section: 'Developer', priority: 40, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'notebook', slug: 'notebook', name: 'Notebooks', icon: 'FileText', href: '/tools/notebook', section: 'Analytics', priority: 50, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
                { id: 'bigquery', slug: 'bigquery', name: 'BigQuery', icon: 'Database', href: '/tools/bigquery', section: 'Analytics', priority: 60, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'ontology', slug: 'ontology', name: 'Ontology', icon: 'Network', href: '/tools/ontology', section: 'Definition', priority: 70, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
            ],
        },
        {
            id: 'fallback-system',
            slug: 'system',
            name: 'Settings',
            icon: 'Settings',
            priority: 30,
            items: [
                { id: 'users', slug: 'users', name: 'Users', icon: 'Users', href: '/admin/users', section: 'Access', priority: 10, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'roles', slug: 'roles', name: 'Roles', icon: 'ShieldCheck', href: '/admin/roles', section: 'Access', priority: 20, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'permission-tester', slug: 'permission-tester', name: 'Permissions', icon: 'Key', href: '/admin/permission-tester', section: 'Access', priority: 25, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'change-requests', slug: 'change-requests', name: 'Change Requests', icon: 'GitBranch', href: '/admin/change-requests', section: 'Access', priority: 28, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'settings', slug: 'settings', name: 'Settings', icon: 'Settings', href: '/admin/settings', section: 'Config', priority: 30, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'audit', slug: 'audit', name: 'Audit Logs', icon: 'FileText', href: '/admin/audit', section: 'Security', priority: 40, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'security', slug: 'security', name: 'Security', icon: 'Shield', href: '/admin/security', section: 'Security', priority: 50, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'notifications', slug: 'notifications', name: 'Notifications', icon: 'Bell', href: '/admin/notifications', section: 'Config', priority: 60, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'themes', slug: 'themes', name: 'Themes', icon: 'Palette', href: '/admin/themes', section: 'Config', priority: 70, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'integrations', slug: 'integrations', name: 'Integrations', icon: 'Zap', href: '/admin/integrations', section: 'Config', priority: 80, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'page-templates', slug: 'page-templates', name: 'Page Templates', icon: 'Layout', href: '/admin/page-templates', section: 'Config', priority: 90, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'space-layouts', slug: 'space-layouts', name: 'Space Layouts', icon: 'Layout', href: '/admin/space-layouts', section: 'Config', priority: 95, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
            ],
        },
        {
            id: 'fallback-infrastructure',
            slug: 'infrastructure',
            name: 'Infrastructure',
            icon: 'Network',
            priority: 25,
            items: [
                { id: 'infra-instances', slug: 'infra-instances', name: 'Instances', icon: 'Server', href: '/infrastructure/instances', section: 'Compute', priority: 10, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'infra-monitoring', slug: 'infra-monitoring', name: 'Monitoring', icon: 'Activity', href: '/infrastructure/monitoring', section: 'Compute', priority: 20, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'storage', slug: 'storage', name: 'Storage', icon: 'HardDrive', href: '/admin/storage', section: 'Storage', priority: 30, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'database', slug: 'database', name: 'Database', icon: 'Database', href: '/admin/database', section: 'Storage', priority: 40, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'cache', slug: 'cache', name: 'Cache', icon: 'Zap', href: '/admin/cache', section: 'Performance', priority: 50, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'backup', slug: 'backup', name: 'Backup', icon: 'History', href: '/admin/backup', section: 'Maintenance', priority: 60, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'logs', slug: 'logs', name: 'Logs', icon: 'FileCode', href: '/admin/logs', section: 'Maintenance', priority: 70, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'kernels', slug: 'kernels', name: 'Kernels', icon: 'Code', href: '/admin/kernels', section: 'Compute', priority: 80, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
            ],
        },
        {
            id: 'fallback-data-management',
            slug: 'data-management',
            name: 'Data Management',
            icon: 'FolderKanban',
            priority: 50,
            items: [
                { id: 'data-models', slug: 'data-models', name: 'Data Models', icon: 'FileText', href: '/admin/data', section: 'Definition', priority: 10, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
                { id: 'assets', slug: 'assets', name: 'Assets', icon: 'Paperclip', href: '/admin/assets', section: 'Content', priority: 15, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
                { id: 'attachments', slug: 'attachments', name: 'Attachments', icon: 'Paperclip', href: '/admin/attachments', section: 'Content', priority: 17, isBuiltin: true, sourcePluginId: null, requiredRoles: ['USER'], isVisible: true },
                { id: 'import-export', slug: 'import-export', name: 'Import/Export', icon: 'Cloud', href: '/admin/import-export', section: 'Tools', priority: 20, isBuiltin: true, sourcePluginId: null, requiredRoles: ['MANAGER'], isVisible: true },
                { id: 'data-governance', slug: 'data-governance', name: 'Data Governance', icon: 'ShieldCheck', href: '/admin/data-governance', section: 'Governance', priority: 25, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'schema-migrations', slug: 'schema-migrations', name: 'Schema Migrations', icon: 'GitBranch', href: '/admin/schema-migrations', section: 'Tools', priority: 35, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'sql-linting', slug: 'sql-linting', name: 'SQL Linting', icon: 'CheckCircle2', href: '/admin/sql-linting', section: 'Tools', priority: 36, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'data-masking', slug: 'data-masking', name: 'Data Masking', icon: 'Eye', href: '/admin/data-masking', section: 'Tools', priority: 37, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
                { id: 'analytics', slug: 'analytics', name: 'Analytics', icon: 'BarChart3', href: '/admin/analytics', section: 'Analysis', priority: 40, isBuiltin: true, sourcePluginId: null, requiredRoles: ['ADMIN'], isVisible: true },
            ],
        },
    ],
}
