apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-config
  namespace: ba-udp
data:
  NODE_ENV: 'production'
  PORT: '8029'
  NEXT_PUBLIC_API_URL: 'https://udp.nccthailand.com/api'
  NEXTAUTH_URL: 'https://udp.nccthailand.com'
  MINIO_ENDPOINT: 'http://minio-service:9000'
  MINIO_PORT: '9000'
  USE_VAULT: 'true'
  VAULT_ADDR: 'http://udp-vault:8200'
  VAULT_SECRET_MOUNT: 'secret'
  PLUGIN_HUB_URL: 'http://udp-pluginhub:3001'
  USE_PLUGIN_HUB: 'true'
  PGRST_DB_SCHEMAS: 'public'
  PGRST_DB_ANON_ROLE: 'anon'
  PGRST_OPENAPI_SERVER_PROXY_URI: 'https://udp.nccthailand.com/api'
  PGRST_DB_MAX_ROWS: '1000'
  MAIN_APP_URL: 'http://udp-app:8029'
