apiVersion: v1
kind: Secret
metadata:
  name: udp-secrets
  namespace: ba-udp
type: Opaque
data:
  DATABASE_URL: 'cG9zdGdyZXM6Ly91ZHA6YTQxNzUyODYzOUBuY2MtcGdzcWwtZGF0YS1wcm9kdWN0LnFzbmNjLmNvbTo1NDMyL3VkcA=='
  NEXTAUTH_SECRET: 'R0h3Q2paSzZ5QUJZY0RzRFJwUVJnYW1ZaDR0cmg3R3U='
  ENCRYPTION_KEY: 'MDAxMTIyMzM0NDU1NjY3Nzg4OTlhYWJiY2NkZGVlZmYwMDExMjIzMzQ0NTU2Njc3ODg5OWFhYmJjY2RkZWVmZg=='
  MINIO_ACCESS_KEY: 'dWRwLXVzZXI='
  MINIO_SECRET_KEY: 'Q0ZFcmJHZ3YzenZrbTNOYTdFeFNQcEpDUVl4WFBDRFc='
  VAULT_TOKEN: 'bjd2aFZBbVhDOXl4TXh2OA=='
  REDIS_PASSWORD: 'RzYzQ1M4MjNlZUs1'
  PGRST_JWT_SECRET: 'dHAzWk1zalJqTmZyR1h6TkEyaHRyWGRHQzhnQmh3Vjk='
  REDIS_URL: 'cmVkaXM6Ly86cmVkaXNwYXNzd29yZEB1ZHAtcmVkaXM6NjM3OQ=='
