export interface BrandingConfig {
  applicationLogo?: string
  applicationLogoType?: 'image' | 'icon'
  applicationLogoIcon?: string
  applicationLogoIconColor?: string
  applicationLogoBackgroundColor?: string
  applicationName: string
  primaryColor: string
  secondaryColor: string
  warningColor: string
  dangerColor: string
  uiBackgroundColor: string
  uiBorderColor: string
  bodyBackgroundColor: string
  topMenuBackgroundColor: string
  platformSidebarBackgroundColor: string
  secondarySidebarBackgroundColor: string
  topMenuTextColor: string
  platformSidebarTextColor: string
  secondarySidebarTextColor: string
  bodyTextColor?: string
  loginBackground: {
    type: 'color' | 'gradient' | 'image' | 'video'
    color?: string
    gradient?: {
      from: string
      to: string
      angle: number
    }
    image?: string
    video?: string
  }
  googleFontsApiKey?: string
  globalStyling: {
    fontFamily?: string
    fontFamilyMono?: string
    borderRadius: string
    borderColor: string
    borderWidth: string
    buttonBorderRadius: string
    buttonBorderWidth: string
    inputBorderRadius: string
    inputBorderWidth: string
    selectBorderRadius: string
    selectBorderWidth: string
    textareaBorderRadius?: string
    textareaBorderWidth?: string
    transitionDuration?: string
    transitionTiming?: string
    shadowSm?: string
    shadowMd?: string
    shadowLg?: string
    shadowXl?: string
    baseFontSize?: string
    inputHeight?: string
    inputPadding?: string
    inputFontSize?: string
    buttonHeight?: string
    buttonPadding?: string
    buttonFontSize?: string
  }
  drawerOverlay?: {
    color: string
    opacity: number
    blur: number
  }
  drawerStyle?: {
    type: 'normal' | 'modern' | 'floating'
    margin?: string
    borderRadius?: string
    width?: string
    backgroundBlur?: number
    backgroundOpacity?: number
  }
  componentStyling: {
    [componentId: string]: {
      backgroundColor?: string
      textColor?: string
      borderColor?: string
      borderRadius?: string
      borderTopLeftRadius?: string
      borderTopRightRadius?: string
      borderBottomRightRadius?: string
      borderBottomLeftRadius?: string
      borderWidth?: string
      borderStyle?: string
      borderTopColor?: string
      borderRightColor?: string
      borderBottomColor?: string
      borderLeftColor?: string
      borderTopWidth?: string
      borderRightWidth?: string
      borderBottomWidth?: string
      borderLeftWidth?: string
      borderTopStyle?: string
      borderRightStyle?: string
      borderBottomStyle?: string
      borderLeftStyle?: string
      padding?: string
      paddingTop?: string
      paddingRight?: string
      paddingBottom?: string
      paddingLeft?: string
      margin?: string
      marginTop?: string
      marginRight?: string
      marginBottom?: string
      marginLeft?: string
      width?: string
      height?: string
      minWidth?: string
      maxWidth?: string
      minHeight?: string
      maxHeight?: string
      fontSize?: string
      fontWeight?: string
      fontStyle?: string
      fontFamily?: string
      letterSpacing?: string
      lineHeight?: string
      textAlign?: string
      textTransform?: string
      textDecoration?: string
      textDecorationColor?: string
      textDecorationThickness?: string
      textDecorationStyle?: string
      textUnderlineOffset?: string
      textUnderlinePosition?: string
      opacity?: string
      backdropFilter?: string
      boxShadow?: string
      filter?: string
      transform?: string
      cursor?: string
      outline?: string
      outlineColor?: string
      outlineWidth?: string
      gap?: string
      zIndex?: string
      overflow?: string
      overflowX?: string
      overflowY?: string
      whiteSpace?: string
      wordBreak?: string
      textOverflow?: string
      visibility?: string
      pointerEvents?: string
      userSelect?: string
      transition?: string
      position?: string
      top?: string
      right?: string
      bottom?: string
      left?: string
      display?: string
      flexDirection?: string
      flexWrap?: string
      justifyContent?: string
      alignItems?: string
      alignContent?: string
      gridTemplateColumns?: string
      gridTemplateRows?: string
      gridColumn?: string
      gridRow?: string
    }
  }
}
