import type { Chatbot } from '@/app/admin/components/chatbot/types'

export function createDefaultChatbotDraft(): Partial<Chatbot> {
  return {
    name: 'New Chatbot',
    folder_id: null,
    website: 'https://example.com',
    description: 'A new AI assistant',
    engineType: 'custom',
    apiEndpoint: 'https://api.openai.com/v1/chat/completions',
    apiAuthType: 'none',
    apiAuthValue: '',
    conversationOpener: 'Hello! How can I help you today?',
    openaiAgentSdkModel: 'gpt-4o',
    deploymentType: 'popover',
    customEmbedDomain: '',
    primaryColor: '#1e40af',
    fontFamily: 'Inter',
    headerTitle: 'New Chatbot',
    headerDescription: 'How can I help you today?',
    headerShowTitle: true,
    headerShowLogo: false,
    headerBgColor: '#1e40af',
    headerFontColor: '#ffffff',
    headerBorderEnabled: true,
    headerBorderColor: '#e5e7eb',
    headerShowClearSession: true,
    widgetPosition: 'bottom-right',
    widgetOffsetX: '20px',
    widgetOffsetY: '20px',
    widgetSize: '60px',
    widgetAvatarStyle: 'circle',
    widgetBackgroundColor: '#1e40af',
    widgetBorderRadius: '50%',
    widgetBorderWidth: '0px',
    widgetBorderColor: 'transparent',
    widgetShadowBlur: '8px',
    widgetShadowColor: 'rgba(0,0,0,0.2)',
    widgetAutoShow: false,
    widgetAutoShowDelay: 3,
    chatBackgroundColor: '#ffffff',
    chatFontColor: '#1f2937',
    chatBorderRadius: '12px',
    userBubbleColor: '#1e40af',
    userBubbleFontColor: '#ffffff',
    botBubbleColor: '#f3f4f6',
    botBubbleFontColor: '#1f2937',
    composerBackgroundColor: '#ffffff',
    composerFontColor: '#1f2937',
    composerPlaceholder: 'Type a message...',
    popoverWidth: '400px',
    popoverHeight: '600px',
    popoverBorderRadius: '16px',
    avatarType: 'icon',
    avatarIcon: 'Bot',
    avatarIconColor: '#ffffff',
    showStartConversation: true,
    enableConversationRenaming: true,
    followUpQuestions: [],
    enableFileUpload: false,
    showCitations: true,
    isPublished: false,
    chatkitOptions: {
      history: {
        enabled: true,
        showDelete: true,
        showRename: true
      }
    }
  } as any
}
